
from pyut.PyutUtils import PyutUtils

from pyut.ui.Action import Action


class SharedIdentifiers:

    [
        ID_MNU_FILE_NEW_PROJECT,
        ID_MNU_FILE_IMPORT, ID_MNU_FILE, ID_MNU_FILE_DIAGRAM_PROPERTIES,
        ID_MNU_FILE_PRINT_SETUP, ID_MNU_FILE_PRINT_PREVIEW, ID_MNU_FILE_PRINT, ID_MENU_FILE_MANAGE_FILE_HISTORY,
        ID_MNU_ADD_PYUT_DIAGRAM, ID_MNU_ADD_OGL_DIAGRAM,
        ID_MENU_GRAPHIC_ERROR_VIEW, ID_MENU_TEXT_ERROR_VIEW, ID_MENU_RAISE_ERROR_VIEW,
        ID_MNU_HELP_INDEX,
        ID_MNU_HELP_WEB, ID_MNU_FILE_EXPORT,
        ID_MNU_EDIT_SHOW_TOOLBAR, ID_ARROW, ID_CLASS,
        ID_REL_INHERITANCE, ID_REL_REALISATION,
        ID_REL_COMPOSITION,
        ID_REL_AGGREGATION, ID_REL_ASSOCIATION,
        ID_MNU_PROJECT_CLOSE, ID_NOTE, ID_ACTOR,
        ID_USECASE, ID_REL_NOTE, ID_TEXT,
        ID_MNU_HELP_VERSION,
        ID_MNU_FILE_NEW_CLASS_DIAGRAM, ID_MNU_FILE_NEW_SEQUENCE_DIAGRAM,
        ID_MNU_FILE_NEW_USECASE_DIAGRAM, ID_SD_INSTANCE,
        ID_MNU_FILE_INSERT_PROJECT, ID_SD_MESSAGE,
        ID_MNU_FILE_REMOVE_DIAGRAM, ID_DEBUG,
        ID_ZOOM_IN, ID_ZOOM_OUT, ID_ZOOM_VALUE,
    ] = PyutUtils.assignID(42)

    ACTIONS = {
        ID_ARROW:           Action.SELECTOR,
        ID_CLASS:           Action.NEW_CLASS,
        ID_NOTE:            Action.NEW_NOTE,
        ID_REL_INHERITANCE: Action.NEW_INHERIT_LINK,
        ID_REL_REALISATION: Action.NEW_IMPLEMENT_LINK,

        ID_REL_COMPOSITION: Action.NEW_COMPOSITION_LINK,
        ID_REL_AGGREGATION: Action.NEW_AGGREGATION_LINK,
        ID_REL_ASSOCIATION: Action.NEW_ASSOCIATION_LINK,
        ID_REL_NOTE:        Action.NEW_NOTE_LINK,
        ID_ACTOR:           Action.NEW_ACTOR,
        ID_TEXT:            Action.NEW_TEXT,
        ID_USECASE:         Action.NEW_USECASE,
        ID_SD_INSTANCE:     Action.NEW_SD_INSTANCE,
        ID_SD_MESSAGE:      Action.NEW_SD_MESSAGE,
        ID_ZOOM_IN:         Action.ZOOM_IN,
        ID_ZOOM_OUT:        Action.ZOOM_OUT,
    }
