
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyut.ui.eventengine.Events import EVENT_NEW_NAMED_PROJECT
from pyut.ui.eventengine.EventType import EventType


class TestEventType(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 16 December 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testBasicCreation(self):

        eventType: EventType = EventType.NewProject
        self.assertIsNotNone(eventType, 'We must be able to create it')

    def testCorrectedEventTypeId(self):

        eventType: EventType = EventType.NewNamedProject

        expectedId: int = EVENT_NEW_NAMED_PROJECT.typeId
        self.assertEqual(expectedId, eventType.value)

    def testEnsureWeHaveDefinedAllTypeIDs(self):
        pass


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestEventType))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
