
# an enum of the supported actions
# TODO make real enumerations
# TODO remove from mediator
[
    ACTION_SELECTOR,
    ACTION_NEW_CLASS,                   # 1
    ACTION_NEW_ACTOR,                   # 2
    ACTION_NEW_USECASE,                 # 3
    ACTION_NEW_NOTE,                    # 4
    ACTION_NEW_IMPLEMENT_LINK,          # 5
    ACTION_NEW_INTERFACE,               # 6
    ACTION_NEW_INHERIT_LINK,
    ACTION_NEW_AGGREGATION_LINK,
    ACTION_NEW_COMPOSITION_LINK,
    ACTION_NEW_ASSOCIATION_LINK,
    ACTION_NEW_NOTE_LINK,
    ACTION_NEW_TEXT,

    ACTION_DESTINATION_IMPLEMENT_LINK,
    ACTION_DESTINATION_INHERIT_LINK,
    ACTION_DESTINATION_AGGREGATION_LINK,
    ACTION_DESTINATION_COMPOSITION_LINK,
    ACTION_DESTINATION_ASSOCIATION_LINK,
    ACTION_DESTINATION_NOTE_LINK,
    ACTION_NEW_SD_INSTANCE,
    ACTION_NEW_SD_MESSAGE,
    ACTION_DESTINATION_SD_MESSAGE,
    ACTION_ZOOM_IN,
    ACTION_ZOOM_OUT
] = range(24)
