
# os: osx

# osx_image: xcode12u

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

dist: bionic

language: python

cache: pip

services:
  - xvfb

python:
  - "3.9.1"

before_install:
  - sudo apt install libgtk-3-dev
  - sudo apt-get install python-wxgtk3.0
  - sudo apt-get install -y  libsdl2-dev

# command to install dependencies
install:
  # pip install -r requirements.txt
  - python --version
  - pip install antlr4-python3-runtime==4.9.3
  - pip install PyGithub==1.55
  - pip install html-testRunner
  - pip install orthogonal==1.1.6
  - pip install pygmlparser==1.0.1
  - pip install pyumldiagrams==2.30.6
  - pip install xmlschema==1.4.2
  # - pip3 install wxPython
  - pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
