
# os: osx

# osx_image: xcode12u

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

dist: focal

language: python

cache: pip

services:
  - xvfb

python:
  - "3.9.0"

before_install:
  - sudo apt install libgtk-3-dev
  - sudo apt-get install python-wxgtk3.0

# command to install dependencies
install:
  # pip install -r requirements.txt
  - sudo apt-get install -y  libsdl2-dev
  - python3 --version
  - pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython
  - pip3 install wxPython
  - pip3 install antlr4-python3-runtime
  - pip3 install fpdf2
  - pip3 install html-testRunner
  - pip3 install networkx
  - pip3 install orthogonal
  - pip3 install pygmlparser
  - pip3 install pyumldiagrams
  - pip3 install xmlschema

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
