#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyut/pyenv-3.10.10/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKnRFWHRDcmVhdGlvbiBUaW1l'
    b'AERpIDQgTXJ6IDIwMDMgMTk6MTg6MDUgKzAxMDDiemgrAAAAB3RJTUUH0wMEEic1A2go/gAA'
    b'AAlwSFlzAAALEgAACxIB0t1+/AAAAARnQU1BAACxjwv8YQUAAAIgSURBVHjapVNPaNNQGP+l'
    b'aTvbMplhq+vqaY55UuZJZYiCCCrz5EVFEJFdvehBEHYQPAnbUISdxPPAw1AolDEmg4F1ovNg'
    b'aafDTuvaaZOsa9LkJS/Zl1SnZVOKPvjlJd+f3/fL970H/OcSWg1ceIB0pYbTjgN4qKp4fGkU'
    b'11uuNHMfOtMr7s81NQLXswf/lJB7gkFlHaccF0cthrgb6gyHItK2uG0EmYfIidLhfhZLoOfg'
    b'MXT2nke4PQ5RjJF3lWAQuvzf2JFAZ+g/cfkFbOM9dPUz1OIUzI01wGWwbYa+47coKgLOfyOY'
    b'GwtYCO0WewZuCJ/m70KXF6HJKYR2xSDt24O2aJI6Z6CUXwTTsgjHBrYUBLyHZbvakWtpoXfw'
    b'pu+ISgl09R1AR/detEUohKtEsI7u/Ql8zT6jjPqWAp/AccW8ulqgt9oPZo2MFZJN4PIvWDKC'
    b'juK1uFmBw+23hcyE5TXId3AKqpcJ1DSzROZy49v8jmQyCnkp3dwDSpqWP8xesPWc5DsskmxQ'
    b'MmfkJHCzsRO5EBAgauVmBWfuYNINhuZeTd5rOBgp0L3KpYYCm6pDhqKWsPwmj/nUawgCik1j'
    b'ZKaRqn77OEQEotcwODS6gAllrYYvuSqKBd3VqpZKk3x5cQxnd7wLM48O2UrxnXju6hCWMrNY'
    b'Wa5zo8bLDsdCvAO3T44g+9eT2C6Gh1c2MPp04rlKJ336yjiGW74s/7o2AQ/QEuOMQm7qAAAA'
    b'AElFTkSuQmCC')

