
from typing import List

from logging import Logger
from logging import getLogger

from datetime import datetime

from org.pyut.general.PyutVersion import PyutVersion


class OglToPython:

    def __init__(self):

        self.logger: Logger = getLogger(__name__)

    def generateTopCode(self) -> List[str]:

        now = datetime.now()

        dateTimeStr: str = now.strftime("%Y-%m-%d %H:%M:%S")
        topCode: List[str] = [
            f'# \n',
            f'# Generated by Pyut Version {PyutVersion.getPyUtVersion()}\n',
            f'# -- La Vida Buena, LLC\n',
            f'# {dateTimeStr}\n',
            f'# \n'
            ]

        return topCode
