
version: '2.1'
orbs:
  python: circleci/python@1.1.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            scripts/runtests.sh
          name: Unit Tests
workflows:
  main:
    jobs:
      - build
