# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAaUlE'
    b'QVQokc1SsQ3AMAhrql7lV7iE81i4qwORRRRVhU71BMTGTpTh7kcHZ4s9BQCiAcB6b6cAgLvz'
    b'gHXM98CLA3kvkTIjuz0KMugQSsbjllF8VjNTVRGpkBe0Ha4KOy4Qq6sOxKev8TPBDffCNlMx'
    b'IHIJAAAAAElFTkSuQmCC')
