#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"c\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A0?\x02\xc4w\xb3psv\xb3\x80\xca\xa3\x02R\x05\xf5P\x00L0\x02\
\n@\x0c\x0cA\x90(\xa6 P\x14\x8b`\x84\x1e6\xc1\x082\x04\xb1\xb9\x93B\xbfc\n\
\xea\x01\x00f\xffS\x84' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/unknown.bmp", wx.BITMAP_TYPE_ANY)

