# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABMElE'
    b'QVQokZVRMaqDQBScFcEqljaWtgu5wBK3MLmCpWhnmcYmIVY2tp7Ae2xhYAMeYLGw9wJ2gmCK'
    b'/SR885PwX/ceM2/ezCNN0+A/Zb6OlmURQkgplVIAKKWMsSAICCEAyEphWZa6rodhYIxRSgEo'
    b'paSUrutGUUQIWSsIIYZhOJ1OADjnAJqm8X2/KAohxH6/N1YEKSVj7PVOxpiUEsCaoJSilHLO'
    b'9XqtwzmnlGpLa8LXWnvQm3QSDw8ArterzuCXwjiOm81G3/rO2zPWaZqOx2PXddvt1nGcd7H+'
    b'EOZ5Pp/PbdsCME0zjuO+7/98nKnReZ4/0JfLZbfbvTNtACjL8na76T7Lsg9oAMY4jl3X6SZN'
    b'08Ph8AENwLBtu6oqz/OSJAnD8DP6mdI0TZZlfUUDuANpyJNFwPbA+QAAAABJRU5ErkJggg==')
