# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAUUlE'
    b'QVQokc1SQQoAIAzK6P9v8md2KEZE1BYEeRpMQd1AMkWQQ+wbQQpZIlnaJGnJAGArAGdLkhrP'
    b'cM4waVyhR423JUvy/g691qmKDfDfL4UFFfFMGyFdizFJAAAAAElFTkSuQmCC')
