#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"#\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A(\x1f\x15PIP\x0f\x8b\xa0\x1e\x8a(DP\x0fU-\xd4\xc1 \xa0\x07\
\x07\xb8Ub7\x13\xbb\xed4\xf1&\xba\xa0\x1e\x00\x82y<\xf6' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/relagregation.bmp", wx.BITMAP_TYPE_ANY)

