#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S04U0V0T\xe7J\x0cV\xd7SHVp\xcaIL\xce\x06\xf3\x14\
\x80<eg\x03\x10\x04\xf3#@|7\x0b7g7\x0b\xa8<*\x80\t\xeaA\x01\xaa`\x04\x18@D\
\xd1\x05#\xf4\xb0\xa9\x04\xa9E\x13\x04\x89\x0fnA\x04@\x08\xa2\x87\x92\x1e\
\x00\xa3NR\xdf' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/new.bmp", wx.BITMAP_TYPE_ANY)

