#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"#\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A(\x1f\x15\x0c\x02A=40X\xdd\x89EP\x0f\x00O\xe3<\xb0' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/relassociation.bmp", wx.BITMAP_TYPE_ANY)
