# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAQUlE'
    b'QVQokWM8cOAAAymAiSTVdNbg4OBAggaIamL0MKGpI9IeEgDjgQMH0EzFHzNMaCoIxiMTsjpi'
    b'Yp1xWCUNIgEAbe4WnEdKhpsAAAAASUVORK5CYII=')
