#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"c\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A0?\x02\xc4w\xb3psv\xb3\x80\xca\xa3\x02\xea\n\xeaa\x15\xd4\
\xd3\xc3"\x18\x11\x01\x14\x86x\x00\x01"\x80@\x0f\xb7JBf\xd2\xc0G\xf8\x05\xf5\
\x00\x8eAB\xac' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/relinheritance.bmp", wx.BITMAP_TYPE_ANY)
