#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wx import BitmapFromXPMData, ImageFromBitmap
import wx
import cPickle, zlib





def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"#\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A(\x1f\x15\x10\x14\xd4\xd3\xd3\xc3\x10\xd4\x83b2\x05\xb1\x9a\
\tS\x87\xaa]\x0f\xa6\x94\x90J\xec\x82z\n\xc49^\x0fA\x92\x14Jz\x00\xadK=<' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/actor.bmp", wx.BITMAP_TYPE_ANY)

