# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAATklE'
    b'QVQokWM8cOAAAymAiSTVdNbg4OBAggYHB4cDBw4Qo4cJrpqBgYEYPYwQdchC+PUwQkyF60Fm'
    b'43QS3CUEVUNtINJsdA1EgkGdNIgEAN04JZx25LwqAAAAAElFTkSuQmCC')
