# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAgklE'
    b'QVQokc2QMQ6AIAxFgXgFpl6GmSPA3kOxwxGYuUwndkbiYIIRiYqDsVuT95r+z1NKbGbEFP2J'
    b'sHS7MabWmnNmjEkphRAhhLGgtS6lnDtQSgGA9/4gIGKMcfjDdgIRnXN7BiK6fr0Bb1sCgGuu'
    b'AbyltNYS0W1o3hG3tfbC0wx/ElbQwTu3geu8CQAAAABJRU5ErkJggg==')
