# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAWElE'
    b'QVQokd2SQQ7AIAgES1/G0+dpHpqSDa5JvXjongzsACoBXDu6t9zHgMxs0Xy17FC55puZAGwl'
    b'lb7kpztoRQ8A7X+KMUBZLWMAHUCZ5+xHmpki4we7NADwmyWei3m5GgAAAABJRU5ErkJggg==')
