#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAYUlE'
    b'QVQokbWSwQ3AMAgDnSqDeTSP5tH6QEpV2qTlEb+Q4EAGmm2UVAJs94gkSFOYpG2SAI6fvaO6'
    b'AEioAUP7gT4i6XKWNAzcgJSIRa8mJODJhz482E7X3L+ll6Hr4lZ97xM8Vibj/H+RxgAAAABJ'
    b'RU5ErkJggg==')

