#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx



def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"c\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A0?\x02\xc4\xb70\xb0000\x80\xca\xa3\x02\x88\xa0\x1e\n\x80\tF\
\xe8\xc1T\xe9)`\x13\xc4\xaa2\x82j\x82\x110\xf7D \x0b\x82\x00\x84\xc2\xa2\x12\
\x8bv\xacf\x12\x14T\xc0\x16 \x98A\xa7\x07\x00\xfcSL\xe5' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/save.bmp", wx.BITMAP_TYPE_ANY)

