# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABY0lE'
    b'QVQokZWSvYrCQBSFz8wGrMYXSKnl1FaDWKgPkMbSn87GThslqWws4xNYWOYJYqEwAVGwGizE'
    b'VrAOFgZCZosBdzfrKnuruZfvMuecGbJer/Gfsn6PtNar1UpKqZQCwDkXQtTrdUIIAJK7QWu9'
    b'WCwul4sQgnMOQCklpbRtu91uE0LyC2EY7na78XhslrXWlFIA0+m0Uqk0Gg2a0yOlFEKYMyHE'
    b'0ACEEFLKJx6UUoPBoFarmbZcLl+v19vtFgSB7/vPTX+v8/n8JiXOuVLKGMuy7CFps9mYDH54'
    b'iOOYMWa0AqCUZlmW8/bR6XTMKEmS4XAYRRFj7HA4aK0ZY/f7fb/fL5dL27Ydx/mKNU3TyWSy'
    b'3W4BWJbV7XZPp9PTh7MM7Xneg3Zdt1qt/hUDBTCbzaIoMv1oNHpBA6BxHB+PR9P0+/1ms/mC'
    b'BkCLxeJ8Pi+VSr1er9Vqvabx+HxJkhQKhbc0gE/9BaV17U9IBgAAAABJRU5ErkJggg==')
