#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"#\x05Cu\xae\xc4`u=\x85d\x05\xa7\x9c\xc4\xe4l0\
O\x01\xc8Sv6\x00A(\x1f\x15PIP\x0f\x8b\xa0\x9e\x9e\x1e\x86\xa0\x9e\x1e\x8a(\
\xc4\xc1h\x00\xb7J\xecfb\xb7\x9d&\xdeD\x17\xd4\x03\x00\x06\x0e=\xac' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/relcomposition.bmp", wx.BITMAP_TYPE_ANY)

