#----------------------------------------------------------------------
# This file was generated by img2py.py
#
#from wxPython.wx import wxBitmapFromXPMData, wxImageFromBitmap
import cPickle, zlib, wx


def getData():
    return cPickle.loads(zlib.decompress(
'x\xda\xd3\xc8)0\xe4\nV74S\x00"S\x05Cu\xae\xc4`\xf5\x08\x85d\x05\xa7\x9c\xc4\
\xe4l0O\x0f\xc8S6\xb4\x00A0_\x01\xc4w6\x00A0?\x1f\xc47\xb0\x00A0\xdf\x1f\xc4\
720212\x80\xaaG\x05T\x13\xd4\xd3\x8b\x88\xd0\xd3C\x11\xcc\x8f\x80(\x8a\xd0C\
\x08\xfa#\xf4\xfa\xc3\x05\xf3\x11\x82\xf9\xf8\x05\xb1jW\xd0\xc3b\x11v\'Q\xd9\
\xefz\x00F\xa1J\x9d' ))

def getBitmap():
    return getImage().ConvertToBitmap()

def getImage():
    return wx.Image("img/system.bmp", wx.BITMAP_TYPE_ANY)

