# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bitmap = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAYElE'
    b'QVQokZ2QQQrAMAgETenD9uk+rQdBihkDxpOI4+663N0m9Yy2zezFqaRodn0AJOXev7+0NAYW'
    b'fumQgRViD2+BQp5HEbZk9J+TpUMxEOeLtxZIM8hUoFjfmTZ0V+PQH0LkMaB93pTRAAAAAElF'
    b'TkSuQmCC')
