#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-pyenv-3.8.2/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA'
    b'+UlEQVRYhe2WPQ7CMAxGXxEzY+FUsAOCBQY4RQ9CmfmR4A5QTlT2MtRFBcUtEaFh6JO82HL8'
    b'yXGsQEuLZwLFnzVVr/OjQh/TrYlrHbJF7aj3DlQJ2DemwsCB+uuxIcNysKuKB8AcuAF3sQSY'
    b'Uf2qrF9WpPjj0oHvtnUlIFISRuJPgQXQBwbAUnwZMPlWQFHclHAW/8oQW0ks+UZAuXiVhYbc'
    b'UGJ3GwHe94CJCF3xCf0K1hK7GmLOhnDI6xD2xMpDOHYhoBBhYoM+G7GS43wRTclbnYpdyJ+f'
    b's0V0rBFhi7WADNj5FuDyV/S/e6Dunn/1N3zivQMtLd55AH4CYXYHl+1EAAAAAElFTkSuQmCC')
