# ----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-3.7.3-wxPython/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage: PyEmbeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAg0lE'
    b'QVQokZVS2w0AIQyCyw3W0Rytm/U+Gms1ng8+DIm0QJSqihu862sRcRJ7VwMiEjrnIsLzSO72'
    b'/ln/ZaMbmQEwgOREnbdEBwMImBmD+znseCoZdensMDrUVKxbugJ5oKlLmdYGgFJaJAOwVatq'
    b'czhRI0ofqnOH1UB+h4uv4Xj2kh4fB18/O2omdhYAAAAASUVORK5CYII=')
