#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/venv-pyenv-3.9.0/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABhGlDQ1BJQ0MgcHJvZmlsZQAA'
    b'KJF9kT1Iw1AUhU9TpSIVETuIOGSoulgQFXHUKhShQqgVWnUweekfNGlIUlwcBdeCgz+LVQcX'
    b'Z10dXAVB8AfEzc1J0UVKvC8ptIjxwuN9nHfP4b37AKFeZprVMQ5oum2mEnExk10VQ68IoA/A'
    b'KGZkZhlzkpSEb33dUzfVXYxn+ff9WT1qzmJAQCSeZYZpE28QT2/aBud94ggryirxOfGYSRck'
    b'fuS64vEb54LLAs+MmOnUPHGEWCy0sdLGrGhqxFPEUVXTKV/IeKxy3uKslauseU/+wnBOX1nm'
    b'Oq0hJLCIJUgQoaCKEsqwEaNdJ8VCis7jPv5B1y+RSyFXCYwcC6hAg+z6wf/g92yt/OSElxSO'
    b'A50vjvMxDIR2gUbNcb6PHadxAgSfgSu95a/UgZlP0mstLXoE9G4DF9ctTdkDLneAgSdDNmVX'
    b'CtIS8nng/Yy+KQv03wLda97cmuc4fQDSNKvkDXBwCIwUKHvd591d7XP7t6c5vx+Gj3Kv11u/'
    b'sgAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOnAAADpwBB5RT3QAAAAd0SU1FB+UBEQAs'
    b'FQt0tp4AAADSSURBVFjD7ZbdDcIgFEY/CEM4BiMwCo8+MoFenYBHx2EExnAK8cVrGtIfq+Vq'
    b'Iidp0qQN9/C1XAA6nX9H8U2MseScxQpbaxFCeNaH974AELse9WBqM+ccnHNvzyylhJTS5Dj8'
    b'nBkVOB72H8XLAlPjDAX01t+WiBQRAQBO5wuU3qm59zcXKLdr4ZkTEYioiAqsTaKZwKtJ6Nbr'
    b'vU5i+AOOroIWSXBxFhFNoE6i7g1GSoCTaN4H1tIFvi5g5jaKFiz2gXq7FEvAWgvvveiJqNPp'
    b'/AR3fsh6H/5KEqEAAAAASUVORK5CYII=')

