
from enum import Enum


class EventType(Enum):
    """
    UpdateApplicationTitleEvent
        Updates the application title
        parameters:
            newFilename: str
            currentFrameZoomFactor : float
            projectModified : bool

    UpdateApplicationStatusEvent
        Updates the application status bar
        parameters:
            applicationStatusMsg:  The new message to display

    RemoveDocumentEvent
        Removes the currently selected document

    NewNamedProjectEvent
        Creates a new project in the project manager and the appropriate UI elements
        parameter:
            projectFilename:  The fully qualified filename
            eventHandler:         The eventHandler to return the IPyutProject object

    InsertProjectEvent
        parameter:
            projectFilename:  The fully qualified filename

    NewDiagramEvent
        Creates a new diagram on the current project
        parameter:
            diagramType:   A value from the DiagramType enumeration

    NewProjectDiagramEvent
        Creates a new diagram for the given project;  Includes the UI and model artifacts
        parameters:
            NewProjectDiagramInformation

    CutShapeEvent
        Cuts only the specified shape
        parameter:
            shapeToCut

    EditClassEvent
        Invokes the Edit Class dialog
        parameter:
            pyutClass

    EditNoteEvent
        Invokes the Edit Note dialog
        parameter:
            pyutNote

    EditTextEvent
        Invokes the Edit Text dialog
        parameter:
            pyutText

    EditActorEvent
        Invokes a general Edit dialog for the name
        parameter:
            pyutActor

    AddShapeEvent
        Adds the specified shape on the UI
        parameter:
            oglObject      The Ogl document to place on the UML UmlFrame

    SelectToolEvent
        Use to select tools in the toolbar as a visual-aid to the end-user/developer
        parameter:
            toolId - The tool id;  The value generated by wx.NewIdRef

    SetToolActionEvent
        Used to set the appropriate tool action for the ActionHandler.
        Parameter
            action The action identifier from Actions

    MiniProjectInformationEvent:
        Used to get some project data;
        parameters
            eventHandler – Callback that is invoked with a parameter of type MiniProjectInformation

    ActiveUmlFrameEvent
        Used to retrieve the currently active frame
        parameters:
            eventHandler - Callback this is invoked with a parameter of type UmlDiagramsFrame

    ActiveProjectInformationEvent
        Used to get information on the active project so that the UML Object edit dialogs
        can do their job
        parameters:
            eventHandler - Callback that is invoked with a parameter of type ActiveProjectInformation

    FrameInformationEvent
        Use by the plugin adaptor to provide low level to plugins that need item
        parameters:
            eventHandler - Callback this is invoked with a parameter of type FrameInformation

    UpdateEditMenuEvent
        Used to update the Edit menu Undo/redo menu items.  This involves using the
        command processor associated with each Uml Frame
        parameters:
            commandProcessor - The command processor associated with the currently visible UML Frame

    AssociateEditMenuEvent:
        Used on the initial creation of a Unified Modeling Language (UML) frame to associate it with the Edit Menu
        parameters:
            commandProcessor - The command processor associated with the currently visible UML Frame

    ClassNameChangedEvent:
        Used if a dialog or some code changes a class name.  We have to update the model and the
        model
        parameters:
            oldClassName - the old class name
            newClassName – the new class name

    Events with no parameters get stuffed into the enumeration as instances, so they can be used
    event engine simple send method;  To simplify enumeration creation I create instances for all
    event types
    """

    NewProject               = 'NewProject'
    NewNamedProject          = 'NewNamedProject'
    NewDiagram               = 'NewDiagram'
    NewProjectDiagram        = 'NewProjectDiagram'
    DeleteDiagram            = 'DeleteDiagram'
    OpenProject              = 'OpenProject'
    InsertProject            = 'InsertProject'
    SaveProject              = 'SaveProject'
    SaveProjectAs            = 'SaveProjectAs'
    CloseProject             = 'CloseProject'
    UpdateTreeItemName       = 'UpdateTreeItemName'
    UpdateApplicationTitle   = 'UpdateApplicationTitle'
    UpdateApplicationStatus  = 'UpdateApplicationStatus'
    UpdateRecentProjects     = 'UpdateRecentProjects'
    UMLDiagramModified       = 'UMLDiagramModified'
    SelectAllShapes          = 'SelectAllShapes'
    DeSelectAllShapes        = 'DeSelectAllShapesEvent'
    AddShape                 = 'AddShapeEvent'
    CopyShapes               = 'CopyShapes'
    PasteShapes              = 'PasteShapes'
    CutShapes                = 'CutShapes'
    Undo                     = 'Undo'
    Redo                     = 'Redo'
    CutShape                 = 'CutShape'
    AddPyutDiagram           = 'AddPyutDiagram'
    AddOglDiagram            = 'AddOglDiagram'
    SelectTool               = 'SelectTool'
    SetToolAction            = 'SetToolAction'
    MiniProjectInformation   = 'MiniProjectInformation'
    ActiveUmlFrame           = 'ActiveUmlFrame'
    ActiveProjectInformation = 'ActiveProjectInformation'
    GetLollipopInterfaces    = 'GetLollipopInterfaces'
    EditClass                = 'EditClass'
    EditNote                 = 'EditNote'
    EditText                 = 'EditText'
    EditActor                = 'EditActor'
    EditUseCase              = 'EditUseCase'
    EditInterface            = 'EditInterface'
    FrameInformation         = 'FrameInformation'
    FrameSize                = 'FrameSize'
    SelectedOglObjects       = 'SelectedOglObjects'
    RefreshFrame             = 'RefreshFrame'
    UpdateEditMenu           = 'UpdateEditMenu'
    AssociateEditMenu        = 'AssociateEditMenu'
    ClassNameChanged         = 'ClassNameChanged'
    RequestCurrentProject    = 'RequestCurrentProject'
    DeleteLink               = 'DeleteLink'
    CreateLink               = 'CreateLink'

    OverrideProgramExitSize     = 'OverrideProgramExitSize'
    OverrideProgramExitPosition = 'OverrideProgramExitPosition'

    NOT_SET = 'Not Set'
