
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyut.preferences.PyutPreferences import PyutPreferences

# from pyut.ui.CurrentDirectoryHandler import CurrentDirectoryHandler


class TestCurrentDirectoryHandler(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo - Humberto A. Sanchez II
        Generated: 18 January 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        PyutPreferences.determinePreferencesLocation()

    def setUp(self):
        super().setUp()

        self._preferences: PyutPreferences = PyutPreferences()

    def tearDown(self):
        super().tearDown()

    # def testSingletonBehavior(self):
    #
    #     # saveDiagramsDirectory: str = self._preferences.diagramsDirectory
    #
    #     instance1: CurrentDirectoryHandler = CurrentDirectoryHandler()
    #     instance2: CurrentDirectoryHandler = CurrentDirectoryHandler()
    #
    #     # self._preferences.diagramsDirectory = saveDiagramsDirectory
    #
    #     self.assertEqual(instance1, instance2, 'Ouch no longer a Singleton')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestCurrentDirectoryHandler))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
