
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyut.preferences.PyutPreferencesV2 import PyutPreferencesV2

# from pyut.ui.CurrentDirectoryHandler import CurrentDirectoryHandler


class TestCurrentDirectoryHandler(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 18 January 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        self._preferences: PyutPreferencesV2 = PyutPreferencesV2()

    # TODO Broken when run as part of all unit tests;  Works standalone

    def tearDown(self):
        super().tearDown()

    # def testSingletonBehavior(self):
    #
    #     instance1: CurrentDirectoryHandler = CurrentDirectoryHandler()
    #     instance2: CurrentDirectoryHandler = CurrentDirectoryHandler()
    #
    #     self.assertEqual(instance1, instance2, 'Ouch no longer a Singleton')
    # def testGetPreferenceValue(self):
    #
    #     expectedValue: str = self._preferences.diagramsDirectory
    #     self.logger.info(f'{expectedValue=}')
    #
    #     cdh: CurrentDirectoryHandler = CurrentDirectoryHandler()
    #
    #     actualValue: str = cdh.currentDirectory
    #
    #     self.assertEqual(expectedValue, actualValue, 'We did not get preferences value')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestCurrentDirectoryHandler))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
