
from pyut.PyutUtils import PyutUtils

from pyut.ui.Action import Action


class SharedIdentifiers:

    [
        ID_MENU_FILE_NEW_PROJECT,
        ID_MENU_FILE_IMPORT, ID_MENU_FILE_EXPORT,
        ID_MENU_FILE, ID_MENU_FILE_DIAGRAM_PROPERTIES,
        ID_MENU_FILE_PRINT_SETUP, ID_MENU_FILE_PRINT_PREVIEW, ID_MENU_FILE_PRINT, ID_MENU_FILE_MANAGE_FILE_HISTORY,
        ID_MENU_FILE_PROJECT_CLOSE,
        ID_MENU_FILE_NEW_CLASS_DIAGRAM, ID_MENU_FILE_NEW_SEQUENCE_DIAGRAM,
        ID_MENU_FILE_NEW_USECASE_DIAGRAM,
        ID_MENU_FILE_INSERT_PROJECT,
        ID_MENU_FILE_REMOVE_DIAGRAM,

        ID_MENU_EDIT_ADD_PYUT_DIAGRAM, ID_MENU_EDIT_ADD_OGL_DIAGRAM,
        ID_MENU_GRAPHIC_ERROR_VIEW, ID_MENU_TEXT_ERROR_VIEW, ID_MENU_RAISE_ERROR_VIEW,
        ID_MENU_EDIT_SHOW_TOOLBAR,

        ID_MENU_HELP_VERSION, ID_MENU_HELP_WEB, ID_MENU_HELP_DEBUG,

        ID_SD_INSTANCE, ID_SD_MESSAGE,
        ID_ARROW, ID_CLASS,
        ID_NOTE, ID_ACTOR,
        ID_USECASE, ID_REL_NOTE, ID_TEXT,
        ID_RELATIONSHIP_INHERITANCE, ID_RELATIONSHIP_REALIZATION, ID_RELATIONSHIP_COMPOSITION, ID_RELATIONSHIP_AGGREGATION, ID_RELATIONSHIP_ASSOCIATION,
        ID_ZOOM_IN, ID_ZOOM_OUT, ID_ZOOM_VALUE,
    ] = PyutUtils.assignID(41)

    ACTIONS = {
        ID_ARROW                   :           Action.SELECTOR,
        ID_CLASS                   :           Action.NEW_CLASS,
        ID_NOTE                    :            Action.NEW_NOTE,
        ID_RELATIONSHIP_INHERITANCE: Action.NEW_INHERIT_LINK,
        ID_RELATIONSHIP_REALIZATION: Action.NEW_IMPLEMENT_LINK,

        ID_RELATIONSHIP_COMPOSITION: Action.NEW_COMPOSITION_LINK,
        ID_RELATIONSHIP_AGGREGATION: Action.NEW_AGGREGATION_LINK,
        ID_RELATIONSHIP_ASSOCIATION: Action.NEW_ASSOCIATION_LINK,
        ID_REL_NOTE                :        Action.NEW_NOTE_LINK,
        ID_ACTOR                   :           Action.NEW_ACTOR,
        ID_TEXT                    :            Action.NEW_TEXT,
        ID_USECASE                 :         Action.NEW_USECASE,
        ID_SD_INSTANCE             :     Action.NEW_SD_INSTANCE,
        ID_SD_MESSAGE              :      Action.NEW_SD_MESSAGE,
        ID_ZOOM_IN                 :         Action.ZOOM_IN,
        ID_ZOOM_OUT                :        Action.ZOOM_OUT,
    }
